# Generated by Django 2.2.2 on 2019-07-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(max_length=30)),
                ('IDUser', models.CharField(max_length=30)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
                ('UsedAt', models.DateTimeField()),
                ('CancelledAt', models.DateTimeField()),
            ],
        ),
    ]
