# Generated by Django 2.2.2 on 2019-07-03 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='UUID',
        ),
        migrations.AlterField(
            model_name='booking',
            name='CancelledAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='IDUser',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='UsedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
